name: James Jellings
favicon: null
layout_spectrum: 0.09144839132204652
typography_spectrum: 0.84422498033382
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.36625101370736957
  lightness: 0.5657001186627895
  saturation: 0.47499204124324024
  rhythmicContrast: 0.24055982823483646
purpose: []
