analytics:
  twitter: null
  google: null
  facebook: null
name: James Jellings
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
typography_spectrum: 0.84422498033382
color:
  saturation: 0.483871
  brandStrength: 0
  lightness: 0.4928315
  brandColors:
    - '#5C4131'
    - '#DEB680'
    - '#D0C5BD'
    - '#657730'
    - '#FDD5AD'
  rhythmicContrast: 0.5555556
layout_spectrum: 0.09144839132204652
cta:
  bucket: null
  version: null
  domain: null
favicon: null
