name: James Jellings
favicon: null
layout_spectrum: 0.43127
typography_spectrum: 0.67432
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: description test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1e1e02'
    - '#393f0c'
    - '#4f7240'
    - '#475710'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
